services:

  frontend:
    image: node:latest
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - common-network
    volumes:
      - "../:/goku"
    command: ["yarn", "--cwd", "/app/frontend/admin", "start"]

  backend:
    image: golang:latest
    depends_on:
      - database
    ports:
      - 8080:8080 # Rest API
      - 8081:8081 # Gateway (Graphql)
    networks:
      - common-network
    volumes:
      - "../:/goku"
    working_dir: /goku
    #command: ["ls", "/goku"]
    command: ["make", "-C", "goku-example-one", "run-backend"]

  
  database:
    image: postgres:alpine3.15
    ports:
      - 5432:5432
    networks:
      - common-network
    volumes:
      - "../:/goku"
    environment:
      - POSTGRES_PASSWORD=postgres
    command: ["postgres"]

networks:
  common-network:


    


