FROM golang:latest

#Accept input argument from docker-compose.yml
ARG SSH_PRIVATE_KEY

#Pass the content of the private key into the container
RUN mkdir /root/.ssh/
RUN echo "${SSH_PRIVATE_KEY}" > /root/.ssh/id_rsa

#Github requires a private key with strict permission settings
RUN chmod 600 /root/.ssh/id_rsa

#Add Github to known hosts
RUN touch /root/.ssh/known_hosts
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts

WORKDIR /app/backend

# Update the Go Mods file
# RUN cd /app/backend
# RUN go mod tidy

# # Download the Go Mods
# RUN go mod download

# Command: from docker-compose
CMD [ "ls" ]